
FIND_PATH(SPDLOG_INCLUDE_DIR NAMES cfg HINTS ${CMAKE_SOURCE_DIR}/../../SDK/spdlog/include)
FIND_FILE(SPDLOG_DEBUG_LIB spdlogd.lib HINTS ${CMAKE_SOURCE_DIR}/../../SDK/spdlog/lib)
FIND_FILE(SPDLOG_RELEASE_LIB spdlog.lib HINTS ${CMAKE_SOURCE_DIR}/../../SDK/spdlog/lib)
