
FIND_PATH(GLOG_INCLUDE_DIRS NAMES glog HINTS ${CMAKE_SOURCE_DIR}/../../SDK/glog/include)
FIND_PATH(GLOG_LIB_DIR NAMES glog.lib HINTS ${CMAKE_SOURCE_DIR}/../../SDK/glog/lib)
SET(GLOG_LIBRARIES ${GLOG_LIB_DIR}/glog.lib)

FIND_PATH(GFLAGS_INCLUDE_DIRS NAMES gflags HINTS ${CMAKE_SOURCE_DIR}/../../SDK/gflags/include)
FIND_PATH(GFLAGS_LIB_DIR NAMES gflags.lib HINTS ${CMAKE_SOURCE_DIR}/../../SDK/gflags/lib)
#SET(GFLAGS_LIBRARIES ${GFLAGS_LIB_DIR}/gflags.lib)
#SET(GFLAGS_LIBRARIES_NO_THREADS ${GFLAGS_LIB_DIR}/gflags_nothreads.lib)
list(APPEND GFLAGS_LIBRARIES "${GFLAGS_LIB_DIR}/gflags.lib")
list(APPEND GFLAGS_LIBRARIES "${GFLAGS_LIB_DIR}/gflags_nothreads.lib")



